//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public string ID { get; set; }
        public string Post { get; set; }
        public string LFP { get; set; }
        public string Login { get; set; }
        public string Passworg { get; set; }
        public Nullable<int> Last_entrance { get; set; }
        public string input_type { get; set; }
    }
}
